name: US Market Signals
on:
  schedule:
    - cron: "*/15 13-20 * * 1-5"   # UTC 13:00–20:59 ≈ 美东09:00–16:59，每15分钟
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install yfinance pandas numpy pytz requests
      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot.py
